import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

//user-defined import files
import {Colors} from '../../../Utils/colors';
import {fonts} from '../../../Utils/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: wp(4),
    backgroundColor: '#fff',
  },
  inerContaiber: {
    flex: 1,
    backgroundColor: '#fff',
    marginHorizontal: wp(4),
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: hp(1.2),
  },
  headerText: {
    fontSize: wp(4),
    color: Colors.black,
    fontFamily: fonts.bold,
  },
  backicon: {
    width: wp(2),
    height: hp(2),
  },
  coverContainer: {
    width: wp(90),
    height: wp(90),
    alignSelf: 'center',
    marginVertical: hp(2.5),
    borderRadius: wp(5),
    overflow: 'hidden',
  },
  speakerIcon: {
    width: wp(5),
    height: wp(5),
    resizeMode: 'contain',
  },
  speechBtn: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: wp(0.2),
    borderColor: Colors.purple,
    borderRadius: wp(4),
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.5),
    marginTop: hp(1),
  },
  playBtn: {
    marginTop: hp(2),
    alignSelf: 'center',
    borderWidth: wp(0.2),
    borderColor: Colors.purple,
    borderRadius: wp(7),
    width: wp(13),
    height: wp(13),
    alignItems: 'center',
    justifyContent: 'center',
  },
  playIcon: {
    width: wp(12),
    height: wp(12),
    resizeMode: 'contain',
  },
  recordingPauseTxt: {
    fontSize: hp(1.4),
    color: Colors.gray,
    fontFamily: fonts.medium,
    marginVertical: hp(1),
    textAlign: 'center',
  },
  recordingView: {
    backgroundColor: Colors.gray2,
    borderRadius: wp(2),
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.5),
  },
  recordingTxt: {
    fontSize: hp(1.4),
    color: Colors.black,
    fontFamily: fonts.medium,
  },
  speechTxt: {
    fontSize: hp(1.6),
    color: Colors.purple,
    fontFamily: fonts.medium,
    marginLeft: wp(1),
  },
  coverImage: {
    width: '100%',
    height: '100%',
  },
  trackInfo: {
    paddingHorizontal: wp(5),
    marginBottom: hp(2.5),
    flexDirection: 'row',
    alignItems: 'center',
  },
  trackTitle: {
    fontSize: hp(2.5),
    fontWeight: '600',
    color: '#1F2937',
  },
  trackSubtitle: {
    fontSize: wp(4),
    color: '#6B7280',
  },
  tabRow: {
    flexDirection: 'row',
    marginBottom: hp(2),
    backgroundColor: Colors.gray2,
    borderRadius: wp(2),
    paddingHorizontal: wp(1.5),
    paddingVertical: hp(0.8),
  },
  tabButton: {
    flex: 1,
    backgroundColor: Colors.gray2,
    borderRadius: wp(2),
    borderBottomWidth: 0,
    borderColor: Colors.purple,
    height: hp(5),
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedTabButton: {
    borderBottomWidth: wp(0.5),
    borderColor: Colors.purple,
    backgroundColor: Colors.white,
  },
  tabText: {
    color: Colors.black,
    fontSize: hp(2),
    fontFamily: fonts.medium,
  },
  selectedTabText: {
    color: Colors.purple,
  },
  stepText: {
    fontSize: hp(2),
    color: '#7B1CFF',
    backgroundColor: '#F3ECFE',
    borderRadius: hp(2),
    paddingHorizontal: hp(1),
    paddingVertical: hp(0.3),
    marginRight: wp(2),
  },
  card: {
    marginBottom: hp(3),
    borderWidth: 1,
    borderColor: '#eee',
    borderRadius: wp(2),
    padding: wp(3),
    backgroundColor: '#faf8ff',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: wp(1.5),
    padding: wp(2),
    marginBottom: wp(2),
    fontSize: wp(4),
    backgroundColor: '#fff',
  },
  ttsButton: {
    backgroundColor: '#e5dbff',
    borderRadius: wp(1.5),
    paddingVertical: hp(1),
    paddingHorizontal: wp(3),
    alignItems: 'center',
    marginBottom: wp(2),
  },
  ttsButtonText: {
    color: '#a259ff',
    fontWeight: '600',
    fontSize: wp(3.8),
  },
  addButton: {
    backgroundColor: '#f3e8ff',
    padding: wp(3),
    borderRadius: wp(2),
    alignItems: 'center',
    marginBottom: hp(2),
  },
  addButtonText: {
    color: '#a259ff',
    fontWeight: '600',
    fontSize: wp(4),
  },
  removeButton: {
    marginTop: hp(1),
  },
  removeButtonText: {
    color: 'red',
    textAlign: 'right',
    fontWeight: '500',
  },
  nextButton: {
    backgroundColor: Colors.purple,
    borderRadius: wp(2),
    alignItems: 'center',
    height: hp(6),
    justifyContent: 'center',
    marginHorizontal: wp(4),
  },
  nextButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: wp(4.2),
  },
  recordIcon: {
    width: hp(8),
    height: hp(8),
    marginBottom: hp(0.5),
    resizeMode: 'contain',
  },
  affrimationContainer: {
    borderWidth: wp(0.2),
    borderColor: Colors.purple,
    borderRadius: wp(2),
    marginBottom: hp(2),
    paddingHorizontal: wp(4),
    paddingVertical: hp(1),
  },
  affrimationInput: {
    fontSize: wp(4),
    color: Colors.black,
    fontFamily: fonts.medium,
    padding: 0,
    borderWidth: wp(0.2),
    marginTop: hp(1),
    paddingHorizontal: wp(2),
    paddingVertical: hp(1),
    borderRadius: wp(2),
    borderColor: Colors.gray2,
    backgroundColor: Colors.gray2,
    height: hp(10),
  },
  affrimationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  affrimationText: {
    fontSize: wp(4),
    color: Colors.black,
    fontFamily: fonts.medium,
  },
  closeImg: {
    width: wp(6),
    height: wp(6),
    resizeMode: 'contain',
  },
  recordText: {
    fontSize: wp(3.8),
    color: '#555',
    marginBottom: hp(0.5),
  },
  recordStateRow: {
    alignItems: 'center',
    marginVertical: hp(1.5),
  },
  aiButton: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#a259ff',
    borderRadius: wp(1.5),
    paddingVertical: hp(1),
    paddingHorizontal: wp(3),
    alignItems: 'center',
    marginBottom: wp(2),
  },
  aiButtonText: {
    color: '#a259ff',
    fontWeight: '600',
    fontSize: wp(3.8),
  },
});
