import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import {Colors} from '../../../Utils/colors';
import {fonts} from '../../../Utils/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp(5),
    paddingTop: hp(2),
    paddingBottom: hp(1),
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  logo: {
    width: wp(40),
    height: hp(8),
    resizeMode: 'contain',
  },
  headerTitle: {
    fontSize: wp(7),
    fontWeight: '700',
    fontFamily: 'serif',
  },
  profileSection: {
    alignItems: 'center',
    marginVertical: hp(3),
    alignSelf: 'flex-start',
    marginHorizontal: wp(5),
    flexDirection: 'row',
  },
  avatar: {
    width: wp(18),
    height: wp(18),
    borderRadius: wp(9),
    marginBottom: hp(1),
  },
  profileName: {
    fontSize: hp(2.5),
    fontWeight: '600',
    marginLeft: wp(2),
  },
  settingsTitle: {
    fontSize: wp(5.5),
    fontWeight: '700',
    marginLeft: wp(6),
    marginBottom: hp(1),
    color: '#666',
  },
  settingsBox: {
    backgroundColor: '#fff',
    borderRadius: wp(4),
    marginHorizontal: wp(4),
    paddingVertical: hp(1),
    marginBottom: hp(2),
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: wp(2),
    shadowOffset: {width: 0, height: 2},
  },
  settingsItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: hp(2),
    paddingHorizontal: wp(4),
    borderBottomWidth: 1,
    borderBottomColor: '#f2f2f2',
  },
  settingsText: {
    flex: 1,
    fontSize: wp(4),
    marginLeft: wp(3),
    color: '#222',
  },
  arrowIcon: {
    width: wp(4.5),
    height: wp(4.5),
    tintColor: '#7c3aed',
  },
  iconShield: {
    width: wp(6),
    height: hp(2.5),
    resizeMode: 'contain',
  },
  iconDoc: {
    width: wp(6),
    height: hp(2.5),
    resizeMode: 'contain',
  },
  iconMail: {
    width: wp(6),
    height: hp(2.5),
    resizeMode: 'contain',
  },
  buttonSection: {
    marginHorizontal: wp(4),
    marginTop: hp(2),
  },
  logoutButton: {
    backgroundColor: '#ff6b6b',
    borderRadius: wp(4),
    paddingVertical: hp(2.2),
    alignItems: 'center',
    marginBottom: hp(1.5),
  },
  logoutButtonText: {
    color: '#fff',
    fontSize: wp(4.5),
    fontWeight: '600',
  },
  deleteButton: {
    backgroundColor: '#e63946',
    borderRadius: wp(4),
    paddingVertical: hp(2.2),
    alignItems: 'center',
  },
  deleteButtonText: {
    color: '#fff',
    fontSize: wp(4.5),
    fontWeight: '600',
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: hp(8),
    borderTopLeftRadius: wp(6),
    borderTopRightRadius: wp(6),
    backgroundColor: '#fff',
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: wp(2),
    shadowOffset: {width: 0, height: -2},
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  navIconHome: {
    width: wp(6),
    height: wp(6),
    borderRadius: wp(3),
    backgroundColor: '#f5f3ff',
    marginBottom: hp(0.5),
  },
  navIconLibrary: {
    width: wp(6),
    height: wp(6),
    borderRadius: wp(1.5),
    backgroundColor: '#f5f3ff',
    marginBottom: hp(0.5),
  },
  navIconStar: {
    width: wp(6),
    height: wp(6),
    borderRadius: wp(3),
    backgroundColor: '#f5f3ff',
    marginBottom: hp(0.5),
  },
  navIconProfile: {
    width: wp(6),
    height: wp(6),
    borderRadius: wp(3),
    backgroundColor: '#7c3aed',
    marginBottom: hp(0.5),
  },
  navLabel: {
    fontSize: wp(3),
    color: '#888',
    marginTop: hp(0.5),
  },
  activeNavLabel: {
    color: '#7c3aed',
    fontWeight: '700',
  },
});
