export const STRINGS = {
  jumpStart: 'JumpStart',
  next: 'Next',
  skip: 'Skip',
  dontWait: 'Don’t wait, Let’s Jumsptart',
  welcome:
    'Welcome to our app, the most convenient and reliable way to get around town.',
  newHere: 'I’m new here',
  alreadyAccount: 'Already have an account',
  signIn: 'Sign In',
  welcomeBack: 'Hi, Welcome back, you’ve been missed',
  emailId: 'Email ID',
  noDataFound: 'No Data Found',
  enterEmailAddress: 'example@gmail.com',
  accountHolderPlaceHolder: 'e.g, John Smith',
  Required_Message: '* Message is required',
  InValid_Message: '* Please fill valid message (more than 4 character)',
  yourMessage: 'Your Message',
  mobileNo: 'Mobile Number',
  emailAddress: 'E-Mail Adress',
  submit: 'Sumbit',
  helpSupport: 'Help & Support',
  supportInfo: 'Your one stop solution center. We are happy to help you.',
  fullName: 'Full Name',
  password: 'Password',
  rememberMe: 'Remember me',
  forgotPassword: 'Forgot Password',
  dontAccount: 'Don’t have an account? ', //Last Space is important
  signUp: 'Sign Up',
  continue: 'Continue',
  createAccount: 'Create Account',
  businessInfo: 'Business Information',
  serviceSpecialties: 'Service Specialties',
  availability: 'Availability',
  businessTutorials: 'Business Tutorials',
  raiseDispute: 'Raise a dispute',
  useFullContent: 'Some useful content here',
  accountDetails: 'Account Details',
  addBankDetails: 'Add you banking details here',
  addWorkingDay: 'Add you working days',
  businessInfo2: 'Fill your business information below',
  fillInfo: 'Fill your information below for registration.',
  name: 'Full Name',
  abn: 'Abn',
  john: 'Ex. John Doe',
  email: 'Email Address',
  accountHolder: 'Account holder’s Name',
  yearExperience: 'Years of Experience',
  nationalPolice: 'National Police check',
  uploadDocuments: 'Upload Documents',
  documentVisa: 'Document Visa',
  drivingLicence: 'Driving License/Passport',
  exampleEmail: 'example@gmail.com',
  mobileNumber: 'Mobile Number',
  mobileNumber2: 'Mobile number',
  vehicleType: 'Vehicle service type',
  selectVehicle: 'Select vehicle',
  selectService: 'Select service',
  residenceArea: 'Residence address',
  enterAddress: 'Enter address',
  confirmPassword: 'Confirm password',
  alreadyAccount2: 'Already have an account? ', //Last space is Required

  //Validation Error Messages
  Required_Name: '* Name is required',
  Required_Bank: '* Bank is required',
  Required_Terms: '* Agree to Terms of service',
  Invalid_Name: '* Please fill Valid Name',
  Required_Email: '* Email is required',
  Required_Abn: '* Abn is required',
  Invalid_Abn: '* Please fill Valid Abn',
  Invalid_Email: '* Please fill Valid Email',
  Required_Situation: '* Situation is required',
  Required_Price: '* Price is required',
  Invalid_Situation: '* Please fill Valid Situation',
  Invalid_Price: '* Please fill Valid Price',
  Required_Password: '* Password is required',
  Required_BranchCode: '* Branch code is required',
  Required_AccountNo: '* Account no is required',
  Invalid_AccountNo: '* Please fill Valid account no',
  Invalid_BranchCode: '* Please fill valid branch code',
  Required_Experience: '* Experience is required',
  Required_Document: '* Document is required',
  Required_ConfirmPassword: '* Confirm password is required',
  Invalid_Password: '* Please fill Strong Password',
  Mismatch_Password: '* Password is mismatch',
  Required_Phone: '* Number is required',
  InValid_Phone: '* Please fill Valid Number',
  Required_Address: '* Address is required',
  InValid_Address: '* Please fill Valid Address',
  TIMEOUT_ERROR_MESSAGE: 'Time Out Error',
  Required_Service: '* Service is required',
  Required_Vehicle: '* Vehicle is required',
  takePhoto: 'Take Photo',
  chooseGallery: 'Choose From Gallery',
  cancel: 'Cancel',

  earnFriend: 'Earn $150 for every friend you Refer',
  getFriend: 'Get a friend to Start using Jumpstart',
  originalSparePart: 'Original Spare Parts',
  extendWarranty: 'Extended warranty with Jumpstart',
  categories: 'Categories',
  viewAll: 'View All',
};
