export const Route = {
  Loader: 'Loader',
  AuthStack: 'BeforeLogin',
  AppStack: 'AfterLogin',
  BottomTab: 'BottomTab',

  //AuthStack Screen
  Intro: 'Intro',
  Login: 'Login',
  Register: 'Register',
  MySublimal: 'MySublimal',

  //AppStack Screen
  Home: 'Home',
  Rating: 'Rating',
  VerseOfTheDay: 'VerseOfTheDay',
  PrayerSession: 'PrayerSession',
  QuizSection: 'QuizSection',
  QuizQuestions: 'QuizQuestions',
  QuizCompletion: 'QuizCompletion',
  QuizSlide: 'QuizSlide',
  ImageSlider: 'ImageSlider',
  Profile: 'Profile',
  Superwall: 'Superwall',
  IntoScreen: 'IntoScreen',
  CoupleGraph: 'CoupleGraph',
  AnimatedCouple: 'AnimatedCouple',
  KnowTheMeaning: 'KnowTheMeaning',
  Library: 'Library',
  PlanDetails: 'PlanDetails',
  SetReminderScreen: 'SetReminderScreen',
  PlanVerseExplanation: 'PlanVerseExplanation',
  BookVerseExplanation: 'BookVerseExplanation',
  BookDetails: 'BookDetails',
  BookReminder: 'BookReminder',
  SoundPlayer: 'SoundPlayer',
  CreateSublyForm: 'CreateSublyForm',
  Affrimation: 'Affrimation',
  CustomizeSublimal: 'CustomizeSublimal',
  CreateSublimalFinal: 'CreateSublimalFinal',
};
